name: Upptime CI
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [upptime]
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pages: write
  id-token: write

jobs:
  monitor:
    name: Check and update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check status
        uses: upptime/uptime-monitor@master
        with:
          command: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Pull latest commits
        run: git pull --rebase origin master

      - name: Update graphs
        uses: upptime/uptime-monitor@master
        with:
          command: graphs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
