name: Upptime CI
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [upptime]
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pages: write
  id-token: write

jobs:
  summary:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upptime
        uses: upptime/uptime-monitor@master
        with:
          command: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  update-graph:
    name: Update graph and badge
    runs-on: ubuntu-latest
    needs: summary
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upptime
        uses: upptime/uptime-monitor@master
        with:
          command: graphs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
